import { FormData } from '@/types/form';

export const FIELD_LABELS: Record<keyof FormData, string> = {
  // Página 1 – General
  companyName: 'Nombre de la empresa',
  contactName: 'Nombre y cargo de quien completa el diagnóstico',
  sector: 'Sector o industria en la que opera',
  businessStage: '¿En qué etapa se encuentra su empresa?',
  teamSize: '¿Cuántas personas forman parte del equipo?',
  revenueRange: 'Facturación anual aproximada',
  businessDescription: '¿A qué se dedica su empresa?',
  automatedProcesses: '¿Ya tienen procesos automatizados?',
  founderDependency: '¿Qué parte del negocio depende directamente de usted?',
  mainChallenge: '¿Cuál es el principal problema que frena el crecimiento hoy?',
  priorityImprovement: '¿Qué debería estar funcionando mejor en 6 meses?',

  // Página 2 – Administración
  docStorageDesc: '¿Cómo se almacenan los documentos oficiales de la empresa?',
  digitalizationDesc: '¿Qué porcentaje de la documentación está digitalizada? ¿Qué sigue en papel?',
  docNamingDesc: '¿Cómo se nombran los documentos? Si necesita encontrar un registro, ¿cómo lo buscarían?',
  docPermissions: '¿Quién se encarga de esa área?',
  billingFlow: '¿Cómo funciona hoy su proceso de facturación?',
  invoiceApproval: '¿Sus facturas son digitales, físicas o usan ambos formatos?',
  clientBillingDesc: '¿Quién lo maneja, con qué herramienta, cómo se envía y quién hace seguimiento de cobro?',
  unpaidHandling: '¿Cómo se gestionan los impagos de clientes?',
  contractSigning: '¿Cómo se firma documentalmente con clientes y proveedores?',
  approvalMethod: '¿El cobro se realiza antes, durante o después del servicio?',
  adminHours: '¿Cuántas horas semanales se dedican a tareas administrativas manuales en total?',
  repetitiveTasks: '¿Qué tareas administrativas se repiten todos los días o todas las semanas? ¿Cuáles consumen más tiempo sin aportar valor real?',
  accumulationPoints: '¿Dónde se acumulan más documentos sin procesar o dónde hay más retrasos frecuentes?',
  adminFriction: '¿Qué tarea administrativa eliminaría si pudiera? ¿Por qué sigue existiendo?',
  adminToolsDesc: '¿Qué herramientas usan para gestionar la administración?',
  dataGlueDesc: '¿Cómo fluye la información entre herramientas? ¿Hay personas que actúan de puente manual entre sistemas?',
  toolOverlapDesc: '¿Cuántas herramientas se solapan o duplican información? ¿Dónde se introduce el mismo dato más de una vez?',
  adminMetricsDesc: '¿Qué KPIs o métricas administrativas miden actualmente? ¿Con qué frecuencia y quién los revisa?',
  dashboardStatus: '¿Existe algún dashboard o panel de control financiero?',
  reportingMethod: '¿Cómo se reportan los resultados financieros a dirección?',
  sensitiveDataDesc: '¿Qué datos sensibles maneja la empresa y dónde se almacenan? ¿Quién puede exportarlos?',
  auditTrail: '¿Se puede auditar o reconstruir cada operación realizada? ¿Queda registro de quién hizo qué y cuándo?',
  inspectionReadiness: 'Si recibieran una inspección fiscal hoy, ¿en cuánto tiempo tendrían lista toda la documentación?',
  contingencyPlanDesc: '¿Qué pasaría si fallara su herramienta principal de gestión o si el contador externo no respondiera durante una semana?',
  adminScaleDesc: 'Si duplicaran el número de clientes mañana, ¿qué parte de la administración colapsaría primero y por qué?',
  adminScaleHiring: '¿El sistema administrativo actual podría soportar ese crecimiento sin contratar más personas?',
  adminKnowledgeRisk: '¿Qué parte del proceso administrativo no está documentada y dependería de que una persona específica lo recuerde?',
  adminPainDesc: '¿Qué problemas administrativos les quita tiempo actualmente? ¿Qué parte sienten que está fuera de control?',
  adminCatastrophicRisk: '¿Qué error administrativo sería catastrófico para la empresa?',
  adminAutomationWish: '¿Qué les gustaría eliminar o automatizar este año si pudieran?',
  adminSuccessDesc: '¿Cómo definirán el éxito de esta auditoría administrativa? ¿Qué tendría que ser diferente?',

  // Página 3 – Ventas
  salesOwnerDesc: '¿Quién es responsable final de ventas y cuántas personas venden en el equipo?',
  salesRolesDesc: '¿Qué roles comerciales existen? ¿Quién genera leads, quién cierra, quién hace seguimiento?',
  salesFounderDep: '¿Qué tan dependiente de una persona es el proceso de ventas?',
  absenceImpact30: 'Si el responsable de ventas desapareciera 30 días, ¿qué pasaría?',
  leadFlowDesc: '¿Por qué canales llegan los leads y dónde se centralizan?',
  responseTime: 'Tiempo de respuesta a un lead nuevo',
  leadAssignment: '¿Cómo se asignan los leads al equipo?',
  scriptExists: '¿Cómo es el primer contacto con un prospecto? ¿Existe algún guión o proceso?',
  qualificationDesc: '¿Cómo califican si un prospecto es viable? ¿Qué criterios usan y quién decide si pasa a siguiente etapa?',
  proposalDesc: '¿Cómo se genera una propuesta? ¿Hay plantilla, cuánto tarda y quién la aprueba internamente?',
  proposalTime: '¿Cuánto tiempo tarda en generarse una propuesta desde que se decide enviarla?',
  proposalTracking: '¿Saben si el cliente abrió la propuesta? ¿Cómo hacen seguimiento tras enviarla?',
  discountAuth: 'Para otorgarle información al cliente nuevo, pero no saben la respuesta, ¿dónde la buscan?',
  closingHandoffDesc: '¿Qué ocurre exactamente cuando se cierra una venta? ¿Cómo queda registrado y cómo se activa la entrega?',
  leadCoolDesc: '¿Dónde se enfrían o pierden los leads habitualmente? ¿En qué momento del proceso ocurre más?',
  salesTimeWaste: '¿Qué tareas comerciales consumen tiempo sin generar valor real?',
  salesKnowledgeRisk: '¿Qué parte del proceso comercial depende demasiado de una sola persona y no está documentada?',
  pipelineDesc: '¿Cómo es el pipeline de ventas? ¿Cuántas etapas tiene y se respetan?',
  pipelineHealth: 'Estado real del pipeline hoy',
  followUpSystem: '¿Cómo se gestiona el seguimiento a prospectos?',
  closeRate: 'Estimación de tasa de cierre actual',
  salesToolsDesc: '¿Qué herramientas utilizan para gestionar el proceso comercial?',
  toolsIntegrationDesc: '¿Estas herramientas están integradas entre sí o funcionan de forma independiente?',
  leadRegistrationDesc: '¿Dónde se registra la información de los leads o clientes potenciales?',
  leadFlowStepByStep: 'Describa paso a paso qué ocurre desde que entra un lead hasta que se convierte en cliente',
  firstContactOwner: '¿Quién gestiona el primer contacto con el lead?',
  firstContactRegistration: '¿Dónde se registra ese primer contacto?',
  afterFirstContactDesc: '¿Qué ocurre después del primer contacto?',
  noSaleFollowUpDesc: '¿Cómo se realiza el seguimiento si el lead no compra inmediatamente?',
  saleClosedCriteriaDesc: '¿En qué momento se considera que una venta está cerrada?',
  saleRegistrationDesc: '¿Dónde se registra esa venta dentro del sistema actual?',
  leadConversionTracking: '¿Pueden medir actualmente cuántos leads entran y cuántos terminan convirtiéndose en clientes?',
  salesMetricsDesc: '¿Qué métricas comerciales miden actualmente? ¿Con qué frecuencia y quién las revisa?',
  revenueVisibility: 'Visibilidad sobre ingresos futuros',
  dealHistoryDesc: '¿Es posible ver el historial completo de una oportunidad o cliente?',
  conversationsRegistrationDesc: '¿Dónde quedan registradas las conversaciones con los clientes?',
  dataIntegrationDesc: '¿Toda la información del cliente está en un mismo sistema o está repartida en varias herramientas?',
  teamTransitionDesc: '¿Si alguien del equipo deja la empresa, sería fácil continuar las conversaciones con sus clientes?',
  dataAccessDesc: '¿Quién tiene acceso a la base de datos de clientes y leads dentro del equipo?',
  salesScaleDesc: 'Si duplicaran el volumen de leads mañana, ¿qué parte del proceso de ventas colapsaría primero y por qué?',
  salesScaleHiring: '¿El sistema de ventas actual soportaría ese crecimiento sin contratar más personas?',
  salesPainDesc: '¿Cuál es el mayor dolor en ventas hoy?',
  salesCatastrophicRisk: '¿Qué error en ventas sería grave para la empresa?',
  salesGoal12m: '¿Qué meta comercial quieren alcanzar en los próximos 12 meses?',
  salesSuccessDesc: '¿Cómo definirán el éxito de esta auditoría de ventas? ¿Qué tendría que ser diferente?',

  // Página 4 – Marketing
  idealClientDesc: '¿Cuál es el perfil de su cliente ideal?',
  valuePropositionDesc: '¿Cuál es su propuesta de valor real? ¿Qué problema concreto resuelven y cómo lo describirían en una frase?',
  differentiationDesc: '¿Qué los diferencia realmente de la competencia? ¿Es un posicionamiento claro o es genérico?',
  mktSalesAlignmentDesc: '¿Marketing y ventas están alineados en quién es el cliente ideal? ¿O cada área tiene una visión diferente?',
  ticketCycleDesc: '¿Cuál es el ticket promedio de venta y el ciclo típico desde que alguien descubre la marca hasta que compra?',
  channelMapDesc: '¿En qué canales tienen presencia activa hoy? ¿Cuál genera más leads y cuál genera más ventas reales?',
  editorialCalendarDesc: '¿Publican con frecuencia definida? ¿Hay calendario editorial o se publica cuando hay tiempo?',
  channelOwnershipDesc: '¿Quién es responsable de cada canal? ¿Hay algún canal que depende completamente del fundador?',
  channelRoiDesc: '¿Qué canal tiene mejor ROI según su percepción? ¿Y cuál sigue activo aunque no se justifique?',
  leadToSalesProcess: '¿Cómo descubre alguien su marca por primera vez? Describa el recorrido más común desde el primer contacto hasta que se convierte en lead',
  leadCaptureDesc: '¿Dónde dejan sus datos los prospectos? ¿Cuántos pasos hay hasta convertirse en lead? ¿Hay algún incentivo o lead magnet?',
  leadHandlingDesc: 'Describa qué ocurre exactamente con un lead desde que entra hasta que llega a ventas',
  leadScoring: '¿Se califica el lead antes de pasarlo a ventas? ¿Cómo?',
  nurtingStatus: '¿Existe nurturing automatizado para leads que no están listos para comprar?',
  mktToSalesHandoffDesc: '¿Cómo se transfiere el lead a ventas? ¿Hay fricción o pérdida de información en ese traspaso?',
  mktSalesFeedbackDesc: '¿Ventas considera que los leads de marketing son de calidad? ¿Marketing recibe feedback de ventas sobre lo que cierra?',
  contentStrategyDesc: '¿Tienen estrategia de contenido definida? ¿Quién decide los temas, con qué objetivo y alineado con qué parte del embudo?',
  contentPerformanceDesc: '¿Qué tipo de contenido producen y cuál convierte mejor según su experiencia? ¿Miden qué piezas generan ventas?',
  contentRepurposeDesc: '¿Se reutiliza el contenido en diferentes formatos y canales? ¿O se produce una vez y se olvida?',
  contentDependencyDesc: '¿La producción de contenido depende de una sola persona? ¿Qué pasaría si esa persona no estuviera?',
  contentType: '¿Qué tipo de contenido manejan?',
  adsMonthlyBudget: '¿Cuánto presupuesto mensual invierten en publicidad?',
  contentFrequency: '¿Con qué frecuencia suben contenido?',
  mktToolsDesc: '¿Qué herramientas usan en marketing? Email, automatización, ads, analytics, CRM... ¿Están integradas entre sí?',
  mktDataFlowDesc: '¿Cómo fluye la información de un lead desde que entra hasta que llega al CRM? ¿Se pierde información entre plataformas?',
  mktDatabaseDesc: '¿Dónde se almacena la base de datos de leads y contactos? ¿Quién tiene acceso y quién puede exportarla?',
  mktMetricsDesc: '¿Qué métricas de marketing miden actualmente? ¿Con qué frecuencia y quién las revisa?',
  mktFunnelMetricsDesc: '¿Saben cuántos leads generan al mes, cuánto cuesta cada lead y cuántos se convierten en clientes?',
  mktDashboardDesc: '¿Tienen dashboard de marketing en tiempo real o trabajan con reportes manuales?',
  prospectFollowUp: 'Nivel de control y visibilidad sobre el rendimiento real de marketing (escala 0-10)',
  lostOpportunities: '¿Dónde se pierden más leads en el embudo? ¿En qué punto exacto cae más la conversión?',
  mktTimeWasteDesc: '¿Qué tareas de marketing son manuales y repetitivas? ¿Dónde se va más tiempo sin generar valor real?',
  mktKnowledgeRiskDesc: '¿Qué parte del embudo o proceso de marketing no está documentada y dependería de que alguien lo recuerde?',
  channelDependencyRiskDesc: '¿Dependen de un solo canal para generar la mayoría de leads? ¿Qué pasaría si ese canal dejara de funcionar mañana?',
  ownedAudienceDesc: '¿Tienen base de datos propia de contactos o dependen completamente de plataformas externas?',
  dataCompliance: '¿Cumplen con la normativa de protección de datos? ¿Hay política de privacidad, consentimiento y gestión de bajas?',
  mktAuditabilityDesc: '¿Se puede auditar el rendimiento por campaña y comparar periodos? ¿Se registran los cambios realizados en campañas?',
  mktScaleDesc: 'Si duplicaran el presupuesto de marketing mañana, ¿tienen sistema para absorber el doble de leads sin perderlos?',
  mktContentScaleDesc: '¿El contenido y el nurturing escalan con el crecimiento o dependen de tiempo humano que no se puede multiplicar?',
  mktScaleHiring: '¿Tienen estructura real para crecer en los próximos meses o necesitaría una transformación importante?',
  mktNotWorkingDesc: '¿Qué canal o acción de marketing sienten que no está funcionando pero siguen haciendo?',

  // Página 5 – Operaciones
  deliverableDesc: '¿Qué recibe exactamente el cliente cuando compra?',
  serviceType: '¿Cuál es el protocolo de la entrega del servicio? Desde que llega un cliente nuevo hasta que lo recibe',
  activeClientsDesc: '¿Cuántos clientes activos tienen ahora mismo y cuántas personas del equipo participan en la entrega?',
  scopeConsistencyDesc: '¿El cliente siempre recibe lo mismo o el servicio varía según el caso?',
  serviceComplexityDesc: '¿Qué parte del servicio genera más complejidad, más tiempo o más fricción interna?',
  onboardingStatus: '¿Tienen un proceso de onboarding definido para nuevos clientes?',
  onboardingFlowDesc: 'Describa paso a paso cómo se maneja un cliente nuevo',
  onboardingBlockerDesc: '¿Qué información necesitan del cliente para empezar? ¿Qué ocurre si el cliente no responde o tarda en mandarla?',
  projectStartDesc: '¿Qué activa el inicio del trabajo? ¿Cómo se registra, quién lo recibe y cómo se asigna internamente?',
  productionFlowDesc: 'Describa las tareas principales de producción en orden. ¿Quién hace cada una y dónde se producen más retrasos o dependencias entre personas?',
  tacitKnowledgeDesc: '¿Qué parte del trabajo depende de conocimiento no documentado que está solo en la cabeza de alguien?',
  deliveryProcessDesc: '¿Cómo se entrega el trabajo al cliente? ¿Dónde se guarda y cómo se comunica la entrega?',
  clientReviewRounds: '¿Cuántas rondas de revisión del cliente hay en promedio?',
  scopeChangeHandling: '¿Cómo se gestionan los cambios o solicitudes fuera del alcance original?',
  qualityControl: '¿Existe un proceso formal de revisión de calidad antes de entregar al cliente?',
  qualityErrorsDesc: '¿Qué errores o problemas se detectan con más frecuencia después de la entrega? ¿Cuánto tiempo se pierde corrigiéndolos?',
  reworkCausesDesc: '¿Qué parte del trabajo genera más retrabajo interno? ¿Por qué se produce ese retrabajo?',
  bottlenecksDesc: '¿Dónde se producen los mayores retrasos en la entrega? ¿Cuáles son las causas más frecuentes?',
  repetitiveOpsDesc: '¿Qué tareas se repiten manualmente en cada proyecto y podrían hacerse de otra forma?',
  opsStressDesc: '¿Qué parte de la operación genera más estrés al equipo? ¿Por qué?',
  opsToolsDesc: '¿Qué herramientas usan para gestionar proyectos, archivos, comunicación interna y comunicación con clientes? ¿Están integradas?',
  opsDataFlowDesc: '¿Cómo fluye la información del cliente a través de las herramientas? ¿Hay personas que hacen de puente manual entre sistemas?',
  toolOverlapOpsDesc: '¿Hay herramientas duplicadas o datos que se introducen en más de un sistema por separado?',
  satisfactionMeasure: '¿Miden la satisfacción del cliente de forma estructurada?',
  clientCommsProactiveDesc: '¿Con qué frecuencia contactan proactivamente al cliente? ¿Hay protocolo de comunicación?',
  complaintHandlingDesc: '¿Cómo gestionan las quejas o problemas? ¿Existe un protocolo formal?',
  repeatedComplaintsDesc: '¿Qué comentarios o quejas se repiten con más frecuencia? ¿Qué genera más insatisfacción en los clientes?',
  serviceDelivery: 'Si duplicaran el número de clientes mañana, ¿qué parte de la operación colapsaría primero y por qué?',
  opsScaleHiring: '¿La operación actual podría soportar ese crecimiento sin contratar más personas?',
  delegationReadinessDesc: '¿Hay documentación suficiente para que alguien nuevo pueda ejecutar el trabajo sin depender de alguien que lo explique?',
  opsScaleBlockerDesc: '¿Qué parte de la operación genera más retrabajo y qué les impide escalar?',
  opsSuccessDesc: '¿Qué resultado justificaría esta auditoría de operaciones? ¿Cómo definirán el éxito?',

  // Página 6 – Visión estratégica
  simplifyTomorrow: 'Si pudieras simplificar algo de tu negocio mañana mismo, ¿qué sería?',
  biggestFrustration: '¿Qué parte del negocio hoy te genera más cansancio o frustración?',
  worksButFragile: '¿Hay algo que sientes que funciona, pero sabes que no está bien del todo?',
  stagnationFeeling: 'Si todo siguiera exactamente igual durante los próximos 12 meses... ¿eso te daría tranquilidad o te preocuparía?',
  stagnationContext: '¿Por qué? ¿Qué hay detrás de esa respuesta?',
  leastControl: '¿En qué área sientes que tienes menos control hoy?',
  leastControlContext: '¿Qué ocurre exactamente en esa área que te genera esa sensación de falta de control?',
  auditSuccessDef: '¿Qué tendría que pasar para que digas: esta auditoría realmente valió la pena?',
  changeReadiness: '¿Estás listo para hacer cambios si vemos que son necesarios?',
  changeReadinessContext: '¿Qué condición o contexto influye en esa respuesta?',
  contactEmail: 'Correo electrónico',
  preferredCallTime: 'Horario preferido para una llamada con el equipo',
};

export function transformFormData(data: FormData): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(data).map(([key, value]) => [
      FIELD_LABELS[key as keyof FormData] ?? key,
      value,
    ])
  );
}
